import { ReactNode } from "react";
import type { Metadata } from "next";
import { Playpen_Sans } from "next/font/google";
import "./catfish.css";
import { UIProvider } from "./contexts/UIContext";
import { CatfishGameProvider } from "./contexts/GameContext";

const playpenSans = Playpen_Sans({
  variable: "--font-playpen-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "The Catfish Game | A Daft Game by Release The Owl 🦉",
  description: "Generated by create next app",
};

export default function CatfishLayout({ children }: { children: ReactNode }) {
  return (
    <UIProvider>
      <CatfishGameProvider>
        <div className={`${playpenSans.variable} bg-[var(--catfish-bg)]`}>
          {children}
        </div>
      </CatfishGameProvider>
    </UIProvider>
  );
}
