import { ReactNode } from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Catfish Game | A Daft Game by Release The Owl 🦉",
  description: "Generated by create next app",
};

export default function CatfishLayout({ children }: { children: ReactNode }) {
  return <div>{children}</div>;
}
